app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', function()
{
	return Redirect::to('admin');
});

Route::controller('admin/estadisticas', 'Admin_EstadisticasController', array(
	'getIndex' => 'estadisticas',
	'getTecnicos' => 'estadisticas/tecnicos',
	'getPendientes' => 'estadisticas/pendientes',
	'getProyectos' => 'estadisticas/proyectos',
	'getOrdenes' => 'estadisticas/ordenes',
	'getFraudes' => 'estadisticas/fraudes'
));

Route::get('admin/recomendaciones', array('as' => 'recomendaciones', function()
{
	return View::make('admin/recomendaciones');
	
}));

Route::resource('admin/import/resultado', 'Admin_ResultadosimporController');

Route::controller('admin/import', 'Admin_ImportController', array(
	'getIndex' => 'import',
	'getConsulta' => 'import/consulta',
	'postFactura' => 'import/factura',
	'postRevisiones' => 'import/revisiones',
	'postSolicitudes' => 'import/solicitudes',
	'postProgramacion' => 'import/programacion',
	'postDevoluciones' => 'import/devoluciones'
));

//Admin de Modelos
	Route::resource('admin/users', 'Admin_UsersController');
	Route::resource('admin/proyectos', 'Admin_ProyectosController');
	Route::resource('admin/municipios', 'Admin_MunicipiosController');
	Route::resource('admin/tecnicos', 'Admin_TecnicosController');
	Route::resource('admin/campanas', 'Admin_CampanasController');
	Route::resource('admin/revisiones', 'Admin_RevisionesController');
	Route::resource('admin/solicitudes', 'Admin_SolicitudesController');

// route to general admin

	Route::get('admin', array('before' => 'auth', 'as' => 'admin', function(){
		$ruta = Route::currentRouteName();
		return View::make('admin/inicio', compact('ruta'));
	}));

// route to show the login form
	Route::get('login', array('uses' => 'HomeController@showLogin'));

// route to process the form
	Route::post('login', array('uses' => 'HomeController@doLogin'));

// route to Logout
	Route::get('logout', array('uses' => 'HomeController@doLogout'));

// route to Login 
	Route::filter('auth', function()
	{
	   if (Auth::guest()) return Redirect::guest('login');
	});

// Rout to Queue

	Route::get('queue/add', 'QueueController@add');

app/views/admin/errors.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong>Por favor corrige los siguentes errores:</strong>
      <ul>
      @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
      @endforeach
      </ul>
    </div>
  @endif

app/views/admin/inicio.blade.php
@extends ('admin/layout')

@section ('title') Estadisticas Sypelc @stop

@section ('breadcrumbs') @stop

@section ('content')
<h1 class="text-danger title">Sistema de Estadisticas Sypelc</h1>
<div class="panel panel-danger">
	<div class="panel-heading"><h2>Administración</h2></div>
	<div class="panel-body">
		<div class="row">
			<div class="col-md-6">
				<div class="panel panel-default">
				  <!-- Default panel contents -->
				  <div class="panel-heading"><h3>Importar Archivos</h3></div>
					  <div class="panel-body">
					    <p>Importa los archivos genearados por EMSA y Sypelc</p>
					    <a href="{{ route('get admin/import') }}" class="btn btn-primary">
					    	<span class="glyphicon glyphicon-plus"></span> 
					    	Importar Archivos
					    </a>
					  </div>
				</div>	
			</div>
			<div class="col-md-6">
				<div class="panel panel-default">
				  <!-- Default panel contents -->
				  <div class="panel-heading"><h3>Estadisticas</h3></div>
					  <div class="panel-body">
					    <p>Genera las estadisticas de Revisiones y PQR de Sypelc</p>
					    </p>
					    <a href="{{ route('estadisticas') }}" class="btn btn-primary">
					    	<span class="glyphicon glyphicon-calendar"></span> 
					    	Ver Estadisticas
					    </a>
					  </div>
				</div>	
			</div>
		</div>
		<div class="row">
			<div class="col-md-12 center-block">
				<div class="panel panel-default">
				  <!-- Default panel contents -->
				  	<div class="panel-heading"><h3>Administrar Datos</h3></div>
					 	<div class="panel-body">
						    <p>Modifica, Agrega y Elimina datos del sistema</p>
						    <a href="{{ route('admin.tecnicos.index') }}" class="btn btn-primary">
						    	<span class="glyphicon glyphicon-user"></span> 
						    	Tecnicos
						    </a>
						    <a href="{{ route('admin.campanas.index') }}" class="btn btn-primary">
						    	<span class="glyphicon glyphicon-list-alt"></span> 
						    	Campañas
						    </a>
						    <a href="{{ route('admin.proyectos.index') }}" class="btn btn-primary">
						    	<span class="glyphicon glyphicon-list-alt"></span> 
						    	Proyectos
						    </a>
							<a href="{{ route('admin.municipios.index') }}" class="btn btn-primary">
								<span class="glyphicon glyphicon-plane"></span> 
								Municipios
							</a>
							<a href="{{ route('admin.revisiones.index') }}" class="btn btn-primary">
								<span class="glyphicon glyphicon-phone"></span> 
								Revisiones
							</a>
							<a href="{{ route('admin.solicitudes.index') }}" class="btn btn-primary">
								<span class="glyphicon glyphicon-phone"></span> 
								Solicitudes
							</a>
					  </div>
				</div>	
			</div>
		</div>
	</div>
</div>

@stop

app/views/admin/layout.blade.php
<!DOCTYPE html>
<html>
  <head>
    <title>@yield('title', 'Aprendiendo Laravel')</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {{-- Bootstrap --}}
    {{ HTML::style('assets/css/bootstrap.min.css', array('media' => 'screen')) }}
    {{ HTML::style('assets/css/themes/base/jquery-ui.css', array('media' => 'screen')) }}
    {{ HTML::style('assets/css/main.css', array('media' => 'all')) }}

    {{-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries --}}
    <!--[if lt IE 9]>
        {{ HTML::script('assets/js/html5shiv.js') }}
        {{ HTML::script('assets/js/respond.min.js') }}
    <![endif]-->
  </head>
  <body>
    {{-- Wrap all page content here --}}
    <div class="page">
      <nav class="navbar navbar-inverse navbar-fixed-top color" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
              <span class="sr-only">Menu Principal</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a href="{{URL::to('admin')}}" class="'navbar-brand pull-left'">{{HTML::image('images/logosypelc.png', 'Estadisticas Spelc', array('width' => 120, 'height' => 48))}}</a> 
           
          </div>
          <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav">
              <li class="active">{{ HTML::link('admin', 'Inicio')}}</li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
            @if(!Auth::check())
              <li>{{ HTML::link('login', 'Iniciar Sesión') }}</li>  
            @else
              <p class="navbar-text" style="font-size:16px;">Hola, {{Auth::user()->username}}</p>
              <li >{{ HTML::link('logout', 'Cerrar Sesión') }}</li>
            @endif
            </ul>
          </div>
      </nav>
      <div class="container wrap">   
        <div class="row">
          <div class="col-md-12">
            @yield('breadcrumbs', Breadcrumbs::render('admin'))
            
            @yield('content', 'sin contenido')
          </div>
        </div>  
      </div>
    </div>


    {{-- jQuery (necessary for Bootstrap's JavaScript plugins) --}}
    {{ HTML::script('assets/js/jquery.js') }}
    {{-- Include all compiled plugins (below), or include individual files as needed --}}
    {{ HTML::script('assets/js/bootstrap.min.js') }}
    {{ HTML::script('assets/js/admin.js') }}
    {{ HTML::script('assets/js/jquery-ui.js') }}

<link id="bs-css" rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">

    <script>
    $(document).ready(function(){
      $(function() {
        $("#content-fecha input").datepicker();
        $('#content-fecha input').datepicker('option', {dateFormat: 'dd/mm/yy'});
      });
      $("#startDate").datepicker({dateFormat: 'dd/mm/yy'});
    });

    </script>

    <script>
      $('form input[type=file]').change(function () {
        $(this).parent().children('button').removeClass('disabled');
      });
    </script>
  </body>
</html>

app/views/admin/layoutform.blade.php
@extends ('admin/layout')

@section ('title') {{ $action.' '.$nombreModelos }} @stop

@section ('content')

  <h1>{{ $action.' '.$nombreModelos }} </h1>

  <p><a href="{{ route('admin.'.$nombreModelos.'.index') }}" class="btn btn-info">Ver Lista de {{$nombreModelos}}</a></p>
  @if ($action == 'Editar')  
    {{ Form::model($modelo, array('route' => array('admin.'.$nombreModelos.'.destroy', $modelo->id), 'method' => 'DELETE', 'role' => 'form')) }}
    <div class="row">
      <div class="form-group col-md-4">
          {{ Form::submit('Eliminar '.$nombreModelos, array('class' => 'btn btn-danger')) }}
      </div>
    </div>
    {{ Form::close() }}
  @endif

{{ Form::model($modelo, $form_data, array('role' => 'form')) }}

  @include ('admin/errors', array('errors' => $errors))

  @include('admin/'.$nombreModelos.'/form' , array($proyectosSelect, $modelo))

  {{ Form::button($action , array('type' => 'submit', 'class' => 'btn btn-primary')) }}    
  
{{ Form::close() }}

@stop

app/views/admin/layoutlist.blade.php
@extends ('admin/layout')

@section ('title') Lista de {{ $nombreModelos }} @stop

@section ('content')

    <h1>Lista de {{ $nombreModelos }}</h1>

    <p><a href="{{ route('admin.'.$nombreModelos.'.create')}}" class="btn btn-primary">Crear Nuevo</a></p>
   	<table class="table table-striped" style="width: 90%">
    <tr>
        @foreach ($nombresAtributos as $nombre)
          <th>{{$nombre}}</th>  
        @endforeach
        <th>Accion</th>
    </tr>
    @foreach ($modelos as $modelo)
    <tr>
        @foreach ($atributos as $atributo)
          <td>{{$modelo->$atributo}}</td> 
        @endforeach
        <td>
          <a href="{{ route('admin.'.$nombreModelos.'.edit', $modelo->id) }}" class="btn btn-primary">
            Editar
          </a>
           <a href="#" data-id="{{ $modelo->id }}" class="btn btn-danger btn-delete">
              Eliminar
          </a>
        </td>
    </tr>
    @endforeach
  </table>
  {{ $modelos->links() }}
  {{ Form::open(array('route' => array('admin.'.$nombreModelos.'.destroy', 'USER_ID'), 'method' => 'DELETE', 'role' => 'form', 'id' => 'form-delete')) }}
{{ Form::close() }}
@stop

app/views/admin/pendientes.blade.php
@extends ('admin/layout')

@section ('title') Estadistica - Esados Pendientes @stop

@section ('content')
<header class="row">
	<h2 class="text-primary">Ordenes de Revision Pendientes</h2>
</header>
<div class="row">
    <div class="col-md-12">
    
		<table class="table table-hover " style="width: 90%">
		    <tr class="active">
		          <th>numeroOrden</th>  
		          <th>fechaGeneracion</th>
		    </tr>
		    @foreach ($pendientes as $pendiente)
		        <td>{{$pendiente->id}}</td> 
		        <td>{{$pendiente->fecha}}</td> 
		    </tr>
		    @endforeach
		</table>
		{{ $pendientes->links() }}
    </div>	
</div>
@stop

app/views/admin/recomendaciones.blade.php
@extends ('admin/layout')

@section ('title') Recomendaciones y Creditos @stop

@section ('content')

<header class="row">
	<h2 class="text-primary">Recomendaciones y Creditos</h2>
</header>
<div class="row">
    <div class="col-md-11">
    	
		<div class="panel panel-primary">
			<!-- Default panel contents -->
			<div class="panel-heading">Recomendaciones</div>
			<div class="panel-body">
				<ul style="font-size:16px; text-align:justify">
					<li > 
						<p>El archivo excel "Consolidado Factura" generado por Sypelc contiene "columnas basura".
							<br>A partir de la columna 44 trae alrededor de 16 columnas más sin contenido, pero que al 
							importarlo genera un gasto innecesario de memoria. 
							<br><b>Antes de subir el archivo por favor</b>
							eliminelas.
						</p>
					</li>
					<li>
						<p>La columna <b> aforo </b> del archivo "Consolidado Factura (que es usada para generar una de 
						las estadisticas de la aplicacion) trae más de el 40% de casillas en 0, nulas o vacias. 
						Lo cual hace que la estadistica sea de mucha desconfianza.
						</p>
					</li>
					<li>
						<p>Los formatos de las distintas casillas de fechas en el archivo "Consolidado Factura" son incoherentes.
						Esto hace que no se puedan ralizar las estadisticas de forma completa teniendo en cuenta rangos de fechas.
						Lo ideal es que todas las casillas tengan el siguiente formato <b>2013/12/31</b>.
						</p>
					</li>
					<li>
						<p>La casilla tecnicos no está estandarizada, <b>hay hasta 5 diferentes nombre para un mismo tecnico</b>, lo cual
						hace que sea casi imposible obtener estadisticas a partir de ellos. Por favor cambiar el nombre del tecnico
						por el número de cedula del mismo. Así el sistema inmediatamente los reconocerá. 
						</p>
					</li>
					<li>
						<p>Antes de importar los archivos verifique que todos los tecnicos, proyectos y municipios se encuentren
						en el sistema. Sino se encuentra puede agregarlo desde la interfaz inicial. 
						</p>
					</li>
				</ul>	
			</div>
		</div>

		<div class="panel panel-primary">
			<!-- Default panel contents -->
			<div class="panel-heading">Creditos</div>
			<div class="panel-body" style="font-size:16px;">
				<p>Desarrollado con: -Lenguaje: <b>PHP</b> -Framework: <b>Laravel 4.0</b> -Bases de Datos: <b>Postgresql</b>
				-Version html: <b>Html5</b> -CSS: <b>Bootstrap</b>	
				</p>
				<p>Ubicación del Proyecto: <b>/var/www/campanas</b></p>
				<p>Desarrollado por: <b>Andrés Mauricio Pinzón</b> -Tw: <b>@andrestntx</b> -Email: <b>andrespinzon@nuestramarca.com</b></p>
				<a href="http://nuestramarca.com/">{{HTML::image('images/firma_andres.jpg')}}</a>
			</div>


		</div>

    </div>	
</div>
@stop