app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', function()
{
	return Redirect::to('admin');
});

Route::controller('admin/estadisticas', 'Admin_EstadisticasController', array(
	'getIndex' => 'estadisticas',
	'getTecnicos' => 'estadisticas/tecnicos',
	'getPendientes' => 'estadisticas/pendientes',
	'getProyectos' => 'estadisticas/proyectos',
	'getOrdenes' => 'estadisticas/ordenes',
	'getFraudes' => 'estadisticas/fraudes'
));

Route::get('admin/recomendaciones', array('as' => 'recomendaciones', function()
{
	return View::make('admin/recomendaciones');
	
}));

Route::resource('admin/import/resultado', 'Admin_ResultadosimporController');

Route::controller('admin/import', 'Admin_ImportController', array(
	'getIndex' => 'import',
	'getConsulta' => 'import/consulta',
	'postFactura' => 'import/factura',
	'postRevisiones' => 'import/revisiones',
	'postSolicitudes' => 'import/solicitudes',
	'postProgramacion' => 'import/programacion',
	'postDevoluciones' => 'import/devoluciones'
));

//Admin de Modelos
	Route::resource('admin/users', 'Admin_UsersController');
	Route::resource('admin/proyectos', 'Admin_ProyectosController');
	Route::resource('admin/municipios', 'Admin_MunicipiosController');
	Route::resource('admin/tecnicos', 'Admin_TecnicosController');
	Route::resource('admin/campanas', 'Admin_CampanasController');
	Route::resource('admin/revisiones', 'Admin_RevisionesController');
	Route::resource('admin/solicitudes', 'Admin_SolicitudesController');

// route to general admin

	Route::get('admin', array('before' => 'auth', 'as' => 'admin', function(){
		$ruta = Route::currentRouteName();
		return View::make('admin/inicio', compact('ruta'));
	}));

// route to show the login form
	Route::get('login', array('uses' => 'HomeController@showLogin'));

// route to process the form
	Route::post('login', array('uses' => 'HomeController@doLogin'));

// route to Logout
	Route::get('logout', array('uses' => 'HomeController@doLogout'));

// route to Login 
	Route::filter('auth', function()
	{
	   if (Auth::guest()) return Redirect::guest('login');
	});

// Rout to Queue

	Route::get('queue/add', 'QueueController@add');

app/controllers/admin/ImportController.php
<?php

class Admin_ImportController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function getIndex()
	{
      	return View::make('admin/import/form');
	}

	public function __construct() {
   		$this->beforeFilter('csrf', array('on'=>'post'));
   		$this->beforeFilter('auth', array('only' => array('postFactura', 'postSolicitudes', 'getIndex', 'postProgramacion', 'postDevoluciones')));
	}

	public function getConsulta(){
		return View::make('admin/import/respuesta');
	}

	public function postTecnicos(){
		if($file = Input::file('archivo')){
			echo 'encontro';
	       	$destinationPath ='/var/www/campanas/public/uploads';
	        $filename = str_random(8).''.$file->getClientOriginalName();
	        $uploadSuccess = Input::file('archivo')->move($destinationPath, $filename);
	        if( $uploadSuccess ){
	        	echo 'subio';
	        	$data = SimpleCsv::import($destinationPath.'/'.$filename);
	        	if($data){
	        		for($i=1; $i<=count($data);$i++){
	        			$valor = new Tecnico;
	        			$valor->id = $data[$i][2];
	        			$valor->nombre = $data[$i][0];
	        			$valor->save();
	        		}	
	        	}
	        }	
		}
	}

	public function  getCombinaciones(){
		$data = SimpleCsv::import('/var/www/campanas/public/uploads/combinaciones.csv');
		if($data){
			echo "subio";
	        for($i=1; $i<count($data);$i++){
	  
	        	$tipo = Tipo::find($data[$i][0]);
	        	if(!$tipo){
	        		$tipo = new Tipo;
	        		$tipo->crear($data[$i][0], str_replace('?', 'N', utf8_decode($data[$i][1])));
	        		$tipo->save();
	        	}

	        	$dependencia = Dependencia::find($data[$i][3]);
	        	if(!$dependencia){
	        		$dependencia = new Dependencia;
	        		$dependencia->id = $data[$i][3];
	        		$dependencia->save();
	        	}

	        	$accion = Accion::find($data[$i][4]);
	        	if(!$accion){
	        		$accion = new Accion;
	        		$accion->crear($data[$i][4], str_replace('?', 'N', utf8_decode($data[$i][5])));
	        		$accion->save();
	        	}

	        	$recomendacion = Recomendacion::find($data[$i][6]);
	        	if(!$recomendacion){
	        		$recomendacion = new Recomendacion;
	        		$recomendacion->crear($data[$i][6], str_replace('?', 'N', utf8_decode($data[$i][7])));
	        		$recomendacion->save();
	        	}

	        	$tipoPQR = TipoPQR::buscar($tipo, $dependencia, $accion);
	        	if(!$tipoPQR){
	        		$tipoPQR = new TipoPQR;
	        		$tipoPQR->crear($tipo, $dependencia, $accion, $data[$i][2]);
	        		$tipoPQR->save();
	        	}

	        	$tipoPQR_has_recomendacion = TipopqrRecomendacion::buscar($tipoPQR, $recomendacion);
	        	if(!$tipoPQR_has_recomendacion){
	        		$tipoPQR_has_recomendacion = new TipopqrRecomendacion;
	        		$tipoPQR_has_recomendacion->crear($tipoPQR, $recomendacion);
	        		$tipoPQR_has_recomendacion->save();
	        	}
	        
	        }	
	    }
	    echo "imprimio";
	}

	public function  getMunicipios(){
		$data = SimpleCsv::import('/var/www/campanas/public/uploads/municipios.csv');
		if($data){
			echo "subio";
	        for($i=0; $i<count($data);$i++){
	        	$valor = new Municipio;
	        	$valor->id = $data[$i][0];
	        	$valor->nombre = $data[$i][1];
	        	$valor->factorDistancia = $data[$i][2];
	        	$valor->save();
	        }	
	    }
	    echo "imprimio";
	}

	public function postValor(){
		echo 'Llego';
		if($file = Input::file('archivo')){
			echo 'encontro';
	       	$destinationPath ='/var/www/campanas/public/uploads';
	        $filename = str_random(8).''.$file->getClientOriginalName();
	        $uploadSuccess = Input::file('archivo')->move($destinationPath, $filename);
	        if( $uploadSuccess ){
	        	echo 'subio';
	        	$data = SimpleCsv::import($destinationPath.'/'.$filename);
	        	if($data){
	        		for($i=0; $i<count($data);$i++){
	        			$valor = new Valor;
	        			$valor->id = $data[$i][0];
	        			$valor->ubicacionRU = $data[$i][1];
	        			$valor->valorUnitario = $data[$i][2];
	        			$valor->puntos = $data[$i][3];
	        			$valor->save();
	        		}	
	        	}
	        }	
		}
	}

	public function postIrregularidad(){
		echo 'entro';
		for($i=1; $i<200;$i++){
			$irregularidad = new Irregularidad;
			$irregularidad->id = $i;
			$irregularidad->save();
		}
	}

	public function postAutogestiones(){

	}

	public function postSuspenciones(){

	}

	public function postFactura(){
		$file = Input::file('archivo');
		$respuesta = Importer::archivo($file, 'fact');
	   	return View::make('admin/import/respuesta', compact('respuesta'));	
	}	

	public function postRevisiones(){
		$file = Input::file('archivo');
		$respuesta = Importer::archivo($file, 'rev');
	   	return View::make('admin/import/respuesta', compact('respuesta'));	
	}

	public function postSolicitudes(){
		$file = Input::file('archivo');
		$respuesta = Importer::archivo($file, 'sol');
	   	return View::make('admin/import/respuesta', compact('respuesta'));	
	}

	public function postProgramacion(){
		$file = Input::file('archivo');
		$fechareal= Importer::obtenerFechaArchivo($file->getClientOriginalName());

		$respuesta = Importer::archivo($file, 'prog', array('fecha' => $fechareal));
	   	return View::make('admin/import/respuesta', compact('respuesta'));			
	}

	public function postDevolucionsistemas(){
		if($file = Input::file('archivo')){ 
			if($ubicacion = Importer::subirArchivo($file)){ // Sube el archivo al servidor
				ini_set('auto_detect_line_endings', true);
	            if (is_file($ubicacion) AND is_readable($ubicacion)) {
	                if (($handle = fopen($ubicacion, "r")) !== false) {
	                	$sypelc = Entidad::find(1);
	        			$ejecutada = Estado::find(3);
	                    while (($line = fgetcsv($handle, null, ';')) !== false) {
	                    	if(is_numeric($data[$i][0]) && $data[$i][2]){
			        			$ejecucion = null;
			        			if($orden = Orden::find($data[$i][0])){
					        		if($estadoOrden = EstadoOrden::buscar($orden, $data[$i][2], $ejecutada, $sypelc)){
					        			$ejecucion = Ejecucion::buscar($estadoOrden);
					        		}
					        	}
					       		else{
					       			$ejecuion = Ejecucion::buscarComoSea($data[$i][2], $data[$i][1], $sypelc);
					       		}	
					       		if($ejecucion){
					       			echo " ejecucion ";
					        		$lugar = LugarDevolucion::find(2);
					        		$devolucion = new Devolucion;
					        		$devolucion->crear($ejecucion, $lugar, $data[$i][2], $data[$i][3], 'N', null);
					        	}
			        		}	
	                    }
	                }
	            }
	        }
	   	}
	}

	public function postDevoluciones(){
		$file = Input::file('archivo');
		$respuesta = Importer::archivo($file, 'dev');
	   	return View::make('admin/import/respuesta', compact('respuesta'));		
	}	


/*public function getProgramaciones(){
		echo "programaciones ";
		$contador= 0;
		$mes=12;
		$year=2013;
		$destinationPath ='/var/www/campanas/public/uploads/programacion';
		$data = null;
		for($dia=1; $dia<8; $dia++){
			if($dia < 10){
				$data = SimpleCsv::import($destinationPath.'/0'.$dia.$mes.$year.'.csv');	
			}
			else{
				$data = SimpleCsv::import($destinationPath.'/'.$dia.$mes.$year.'.csv');	
			}
	        if($data){
	        	for($i=1; $i<count($data);$i++){
	        		if($data[$i][0]){
	        			$contador++;
			        	$fechaReal = $dia.'/'.$mes.'/'.$year;
		        		if ($orden = Orden::find($data[$i][0])) { // Busca si ya existe la orden
		        			$estadoOrden = EstadoOrden::buscar($orden->id, $fechaReal, '2');
			        		if($estadoOrden){ //Busca si ya existe el estado pendiente en esta orden
			        			$estadoOrden->actualizarTecnico($data[$i][16]);	
			        		}
			        		else{
			        			$tecnico = Tecnico::buscarPorNick($data[$i][9]);
			        			$estadoOrden = new EstadoOrden;
			        			$estadoOrden->programar($orden->id, $fechaReal, 2, 1, $tecnico->id); //Crea el estado pendiente para esta orden
			        		}
		        		}
		        		else{
		        			$cliente = Cliente::find($data[$i][1]); //Busca si ya existe el cliente	
		        			if(!$cliente){ //Si no existe el cliente
			        			$municipio = Municipio::buscarPorNombre($data[$i][2]); 
			        			$servicio = Servicio::buscarPorNombre($data[$i][5]);
			        			$cliente = new Cliente; //Crea el cliente
			        			$cliente->crearND($data[$i][1], $municipio->id, $servicio->id, $data[$i][6], $data[$i][3],  $data[$i][4]);
			        		}
			        		$orden = new Orden;
			        		$orden->crearRevision($data[$i][0], $cliente->id, $data[$i][8]);

			        		$tecnico = Tecnico::buscarPorNick($data[$i][9]);
			        		$estadoOrden = new EstadoOrden;
			        		$estadoOrden->programar($orden->id, $fechaReal, 2, 1, $tecnico->id); //Crea el estado pendiente para esta orden
		        		}
		        	}
		        }
		        echo "  contador: " .$contador;
		    }
		}
	}*/

}

app/views/admin/import/form.blade.php
@extends ('admin/layout')

@section ('title') Importar Archivos @stop

@section ('breadcrumbs')
  {{Breadcrumbs::render(Route::currentRouteName())}}
@stop

@section ('content')
	<h1 class="text-danger">Importar Archivos</h1>
  <div class="panel panel-danger">
    <div class="panel-heading col-md-12"><h2 class="col-md-10">Modulo Importar </h2> <div class="col-md-2"><a href="{{ route('admin.import.resultado.index')}}" class="btn btn-danger">Resultados</a></div></div>
    <div class="panel-body ">
      <div class="col-md-6">
        <h3>Archivos Sypelc</h3>
            <div class="panel panel-default">
            <!-- Default panel contents -->
              <div class="panel-heading">Archivo "Consolidado de Factura"</div>
              <div class="panel-body">
                <p>Archivo de consolidado diario de todas las ejecuciones</p>
                {{ Form::open(array('id' => 'importForm', 'action' => 'Admin_ImportController@postFactura', 'method' => 'POST', 'files' => true))}}
                <div class="form-group">
                  {{ Form::file('archivo') }}
                  {{ Form::button('Importar', array('type' => 'submit', 'class' => 'btn btn-primary disabled')) }}    
                  {{ Form::close() }}
                </div>
              </div>
            </div>

            <div class="panel panel-default">
            <!-- Default panel contents -->
              <div class="panel-heading">Importar Archivo "Devoluciones"</div>
              <div class="panel-body">
                <p>Importa el archivo "devoluciones" en formato .csv dilimitado por ;
                </p>
                {{ Form::open(array('id' => 'importForm', 'action' => 'Admin_ImportController@postDevoluciones', 'method' => 'POST', 'files' => true))}}
                <div class="form-group">
                  {{ Form::file('archivo') }}
                  {{ Form::button('Importar', array('type' => 'submit', 'class' => 'btn btn-primary disabled')) }}    
                  {{ Form::close() }}
                </div>
              </div>
            </div>

            <div class="panel panel-default">
            <!-- Default panel contents -->
              <div class="panel-heading">Importar Archivo "Programacion"</div>
              <div class="panel-body">
                <p>Importa el archivo "programación" en formato .csv dilimitado por ;
                </p>
                {{ Form::open(array('id' => 'importForm', 'action' => 'Admin_ImportController@postProgramacion', 'method' => 'POST', 'files' => true))}}
                <div class="form-group">
                  {{ Form::file('archivo') }}
                  {{ Form::button('Importar', array('type' => 'submit', 'class' => 'btn btn-primary disabled')) }}    
                  {{ Form::close() }}
                </div>
              </div>
            </div>
          </div>
      <div class="col-md-6">
        <h3>Archivos EMSA</h3>
            <div class="panel panel-default">
              <!-- Default panel contents -->
              <div class="panel-heading">Importar Archivo "Solicitudes EMSA"</div>
              <div class="panel-body">
                <p>Importa el archivo "solicitudes" en formato .csv dilimitado por ;
                </p>
                {{ Form::open(array('id' => 'importForm', 'action' => 'Admin_ImportController@postSolicitudes', 'method' => 'POST', 'files' => true))}}
                <div class="form-group">
                  {{ Form::file('archivo') }}
                  {{ Form::button('Importar', array('type' => 'submit', 'class' => 'btn btn-primary disabled')) }}    
                  {{ Form::close() }}
                </div>
              </div>
            </div>

            <div class="panel panel-default">
              <!-- Default panel contents -->
              <div class="panel-heading">Importar Archivo "Revisiones de EMSA"</div>
              <div class="panel-body">
                <p>Importa el archivo "revisiones" en formato .csv dilimitado por ;
                </p>
                {{ Form::open(array('id' => 'importForm', 'action' => 'Admin_ImportController@postRevisiones', 'method' => 'POST', 'files' => true))}}
                <div class="form-group">
                  {{ Form::file('archivo') }}
                  {{ Form::button('Importar', array('type' => 'submit', 'class' => 'btn btn-primary disabled')) }}    
                  {{ Form::close() }}
                </div>
              </div>
            </div>
          </div> 
        </div>
    </div>
  </div>
@stop

app/views/admin/import/list.blade.php
@extends ('admin/layout')

@section ('title') Lista de Usuarios @stop

@section ('breadcrumbs') 
    {{Breadcrumbs::render(Route::currentRouteName())}}
@stop

@section ('content')

    <h1 class="text-danger">Lista de Importaciones</h1>
   	<table class="table table-striped">
    <tr>
        <th>Id</th>
        <th>Creación</th>
        <th>Actualización</th>
        <th>Tipo Archivo</th>
        <th>Lineas</th>
        <th>Creadas</th>
        <th>Actualziadas</th>
        <th>Descartadas</th>
        <th>No Sypelc</th>
        <th>No Encontradas</th>
        <th>Ver</th>
    </tr>
    @foreach ($resultados as $resultado)
    <tr>
        <td>{{ $resultado->id }}</td>
        <td>{{ $resultado->created_at }}</td>
        <td>{{ $resultado->updated_at  }}</td>
        <td>{{ $resultado->nombre }}</td>
        <td>{{ $resultado->contadas }}</td>
        <td>{{ $resultado->creadas }}</td>
        <td>{{ $resultado->actualizadas }}</td>
        <td>{{ $resultado->descartadas }}</td>
        <td>{{ $resultado->noSypelc }}</td>
        <td>{{ $resultado->noEncontradas }}</td>
        <td>
          {{HTML::link('admin/import/resultado/'.$resultado->id, 'Ver', array('class' => 'btn btn-primary'))}}

        </td>
    </tr>
    @endforeach
  </table>
  {{ $resultados->links() }}
  {{ Form::open(array('route' => array('admin.users.destroy', 'USER_ID'), 'method' => 'DELETE', 'role' => 'form', 'id' => 'form-delete')) }}
{{ Form::close() }}
@stop

app/views/admin/import/respuesta.blade.php
@extends ('admin/layout')

@section ('title') Importar Archivos @stop

@section ('breadcrumbs')
	{{Breadcrumbs::render(Route::currentRouteName())}}
@stop

@section ('content') 
	<div class="col-md-12">
		@if ($respuesta['error'] == true)
			<div class="alert alert-danger">
				<h1 style="font-size:20px;">
					<span class="glyphicon glyphicon-remove"></span>
					¡Error! - {{$respuesta['mensaje']}}
				</h1>
			</div>
		@else
			<div class="alert alert-success">
				<h1 style="font-size:20px;">
					<span class="glyphicon glyphicon-ok"></span>
					¡Bien! - {{$respuesta['mensaje']}}
				</h1>
			</div>
			<div class="col-md-12">
				<p style="font-size:18px;">
					<span class="glyphicon glyphicon-cog"></span>
					El archivo se está importando actualmente. Puedes conocer su proceso con el siguiente id 
					{{HTML::link('admin/import/resultado/'.$respuesta['id'], $respuesta['id'])}}
				</p>
			</div>
		@endif
	</div>

@stop

app/views/admin/import/see.blade.php
@extends ('admin/layout')

@section ('title') Resultado de Importación -{{$resultado->id}} @stop

@section ('breadcrumbs') 
	{{Breadcrumbs::render(Route::currentRouteName(), $resultado->id)}}
@stop

@section ('content') 
	<div class="col-md-4">
		<h1 style="font-size:19px;">Resultado <b>{{$resultado->id}}</b></h1>
		<table class="table table-hover" style="font-size:16px;">
	        <tr> 
	        	<td>Creada el</td> 
	        	<td>{{ $resultado->created_at }}</td> 
	        </tr>
	        <tr> 
	        	<td>Actualización</td> 
	        	<td>{{ $resultado->updated_at  }}</td> 
	        </tr>
	        <tr> 
	        	<td>Tipo</td> 
	        	<td>{{ Archivo::find($resultado->tipoarchivo)->nombre }}</td> 
	        </tr>
	        <tr> 
	        	<td>Lineas</td> 
	        	<td>{{ $resultado->contadas }}</td> 
	        </tr>
	        <tr> 
	        	<td>Creadas</td> 
	        	<td>{{ $resultado->creadas }}</td> 
	        </tr>
	        <tr> 
	        	<td>Actualizadas</td>
	        	<td>{{ $resultado->actualizadas }}</td>
	        </tr>
	        <tr> 
	        	<td>Descartadas</td> 
	        	<td>{{ $resultado->descartadas }}</td> 
	        </tr>
	        <tr> 
	        	<td>No Sypelc</td> 
	        	<td>{{ $resultado->noSypelc }}</td> 
	        </tr>
	        <tr> 
	        	<td>No Encontradas </td> 
	        	<td> {{ $resultado->noEncontradas }}</td> 
	        </tr>
        </table>
	</div>

	<div class="col-md-8">
		<h3>Lineas descartadas</h3>
		<table class="table table-hover">
			<tr class="active">
			    <th>Numero de Orden</th>  
			    <th>Motivo</th>
			    <th>Veces</th>
			</tr>
			@foreach ($descartadas as $descartada) 
			<tr>
   				<td>{{$descartada->idOrden}}</td>
   				<td>{{$descartada->nombre}}</td>
   				<td>{{$descartada->veces}}</td>
   			</tr>
   			@endforeach
		</table>
	</div>
@stop